language: scala

env: ADOPTOPENJDK=11

matrix:
  include:
  - env: SBT_VERSION="0.13.18" ADOPTOPENJDK=8
    scala: 2.10.7
  - env: SBT_VERSION="1.2.8"   ADOPTOPENJDK=11
    scala: 2.12.8
  - scala: 2.13.0
    script: "sbt \"++${TRAVIS_SCALA_VERSION}!\" library/test"
  - scala: 2.11.12
    script: "sbt \"++${TRAVIS_SCALA_VERSION}!\" library/test"

before_install:
  # adding $HOME/.sdkman to cache would create an empty directory, which interferes with the initial installation
  - "[[ -d $HOME/.sdkman/bin/ ]] || rm -rf $HOME/.sdkman/"
  - curl -sL https://get.sdkman.io | bash
  - echo sdkman_auto_answer=true > $HOME/.sdkman/etc/config
  - source "$HOME/.sdkman/bin/sdkman-init.sh"

install:
  - sdk install java $(sdk list java | grep -o "$ADOPTOPENJDK\.[0-9\.]*hs-adpt" | head -1)
  - unset JAVA_HOME
  - java -Xmx32m -version
  - javac -J-Xmx32m -version

script:
  - sbt "++${TRAVIS_SCALA_VERSION}!" "^^${SBT_VERSION}" test scripted

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt  -name "*.lock"               -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier
    - $HOME/.sbt
